name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install axios fs-extra

      - name: Update GitHub Stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: singhvarun74
        run: |
          node .github/scripts/update-stats.js
          
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update GitHub stats" && git push)
