name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight daily
  workflow_dispatch:     # Allows manual triggering
  push:
    branches: [ main ]   # Updates on push to main branch

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install axios fs-extra

      - name: Update GitHub Stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: singhvarun74  # Replace with your GitHub username
        run: node .github/scripts/update-stats.js
          
      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "🚀 Update GitHub stats" && git push)
